language: python

python:
  - "2.6"
  - "2.7"

install:
  - "sudo apt-get install python-gevent python-dev libevent-dev"
  - "pip install gevent proxytypes --use-mirrors"
  - "pip install ."

script: py.test